[package]
name = "imezx/ballservice"
version = "2.2.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
description = "BallService is a Module with Blade-Ball Psychic based."

[dependencies]
